### ISSUE TITLE
Reimplement recent usage view

### ISSUE THREAD

**Issue by lacolaco** [lacolaco/contributors-img#896]

**Comment by lacolaco** [comment]
How to collect _real_ usage? 

- What is the real usage?
  - Used at README.md in GitHub
  - Not onetime try-out (frequent usage)
- How I can get it?
  - Collect HTTP requests
  - Pick up requests from GitHub referer.
  - Group these by their repository (extract from referer)
  - If a repository sent requests multiple times, mark it as "recent usage"
- What does "recent" means
  - Expire "recent usage" marks in 1 month after the last request.

**Comment by lacolaco** [comment]
## Solution

- Collect request log on the endpoint
  - Cloud Run app -> Cloud Logging -> Big Query
- Query logs and get recent usage repositories periodically
  - Big Query -> Cloud Run -> Cloud Firestore
- Respond data from API
  - Cloud Firestore -> Cloud Run -> webapp

**Comment by lacolaco** [comment]
## TODO

- [ ] Send usage logs from Cloud Run to Cloud Logging
- [ ] Connect Cloud Logging and Big Query (log routing)
- [ ] Add an (internal) endpoint to query usage with BQ API
- [ ] Add an endpoint for webapp to give recent usage data.
